### ISSUE TITLE
enable/disable footer button

### ISSUE THREAD

**Issue by indrahulu** [saribe/eModal#14]
in eModal.ajax, is there a way to make all buttons in footer disabled while loading remote content and then enabled after remote content is successfully loaded. i'm using eModal to load a form and place the submit button in the footer. since the loading of form could possibly take time, i think it could be helpful if there is a way that the submit button in the footer will only be enabled after the form is successfully loaded. i am no javascript expert to figured this out and really like the simple use of eModal. :)

**Comment by saribe** [comment]
No!

That can be a new feature in new next version!

I will try do get it done asap.


*Samuel Ribeiro Pinto*


2015-08-10 13:38 GMT+01:00 indrahulu <notifications@github.com>:

**Comment by saribe** [comment]
This bug is fix thanks to pharaoh2012.

you can download the version 1.2.1-rc1

ATTENTION!!!

The change 1.2.x has breaking changes. The callback argument for prompt, confirm, ajax and iframe, now are provided in then function.

e.g.:
 V 1.1.X
eModal.confirm(question, title, function(trueOrFalse) { trueOrFalse ? doTrue() : doFalse(); });

V 1.2.X
eModal
     .confirm(question, title)
     .then(doTrue, doFalse);
