### ISSUE TITLE
Ajax data should be preserved

### ISSUE THREAD

**Issue by abidalisidd** [saribe/eModal#21]
There should be an option to preserve ajax response so that only first time will perform ajax call, not every time.

**Comment by saribe** [comment]
HI!

BS eModal by design does not support ajax caching because we consider that, http cache requests should not be this module concern, you can get a 403 (not modified) in second request if your http-server allows client to do caching (it only request headers).

try to enable jQuery ajax cache:
    $.ajaxSetup({ cache: true });
        This solution will do not any request if your server allow cache.

Try using fiddler to see Http codes, and make sure in your browser dev tools you don't have the "Disable cache" feature enabled.


http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5
